//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bicycle_Rental_System.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class bicycle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public bicycle()
        {
            this.rentals = new HashSet<rental>();
        }
    
        public int Bicycle_Number { get; set; }
        public Nullable<int> Bicycle_ModelID { get; set; }
        public int Bicycle_Size { get; set; }
        public Nullable<System.DateTime> Bicycle_LastService { get; set; }
        public Nullable<bool> Bicycle_CheckedStatus { get; set; }
    
        public virtual bmodel bmodel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rental> rentals { get; set; }
    }
}
